# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "16e39ea5c00ce8b931f0d050ca32e836"
name = "subscription-app-virender"
handle = "subscription-app-virender"
application_url = "https://broad-ebook-mere-christ.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_own_subscription_contracts,write_products,write_purchase_options"

[auth]
redirect_urls = [
  "https://broad-ebook-mere-christ.trycloudflare.com/auth/callback",
  "https://broad-ebook-mere-christ.trycloudflare.com/auth/shopify/callback",
  "https://broad-ebook-mere-christ.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "https://ampland-technique-roy-due.trycloudflare.com/api/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[app_proxy]
url = "https://broad-ebook-mere-christ.trycloudflare.com/api/subscription"
subpath = "subscription"
prefix = "apps"

[pos]
embedded = false

[build]
dev_store_url = "virendertesting.myshopify.com"
automatically_update_urls_on_dev = true
