# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "07e3473dc2dcdd369e270027501fc1ee"
application_url = "https://dynadealersapp.com"
embedded = true
name = "Dynadealer Raffle app"
handle = "dynadealer-raffle-app"

[build]
automatically_update_urls_on_dev = false
dev_store_url = "dynadealer-test.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,write_orders,read_products,write_own_subscription_contracts,write_products,write_purchase_options"

[auth]
redirect_urls = [
  "https://dynadealersapp.com/auth/callback",
  "https://dynadealersapp.com/auth/shopify/callback",
  "https://dynadealersapp.com/api/auth/callback"
]

[app_proxy]
url = "https://dynadealersapp.com/api/subscription"
subpath = "subscription"
prefix = "apps"

[pos]
embedded = false
