# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e708894b40138257983227c922e97135"
name = "subscription"
handle = "subscription-155"
application_url = "https://contribution-hire-prophet-bay.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "taran-dev-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_orders,write_own_subscription_contracts,write_products,write_purchase_options"

[auth]
redirect_urls = [
  "https://contribution-hire-prophet-bay.trycloudflare.com/auth/callback",
  "https://contribution-hire-prophet-bay.trycloudflare.com/auth/shopify/callback",
  "https://contribution-hire-prophet-bay.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-04"

[app_proxy]
url = "https://contribution-hire-prophet-bay.trycloudflare.com/api/subscription"
subpath = "subscription"
prefix = "apps"

[pos]
embedded = false
