# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "07e3473dc2dcdd369e270027501fc1ee"
name = "Dynadealer Raffle app"
handle = "dynadealer-raffle-app"
application_url = "https://bool-variable-greensboro-electrical.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_own_subscription_contracts,write_products,write_purchase_options"

[auth]
redirect_urls = [
  "https://bool-variable-greensboro-electrical.trycloudflare.com/auth/callback",
  "https://bool-variable-greensboro-electrical.trycloudflare.com/auth/shopify/callback",
  "https://bool-variable-greensboro-electrical.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[app_proxy]
url = "https://bool-variable-greensboro-electrical.trycloudflare.com/api/subscription"
subpath = "subscription"
prefix = "apps"

[pos]
embedded = false

[build]
dev_store_url = "dynadealer-test.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
