# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "07e3473dc2dcdd369e270027501fc1ee"
application_url = "https://publications-hungarian-supporting-appearance.trycloudflare.com"
embedded = true
name = "Dynadealer Raffle app"
handle = "dynadealer-raffle-app"

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_own_subscription_contracts,write_products,write_purchase_options"

[auth]
redirect_urls = [
  "https://publications-hungarian-supporting-appearance.trycloudflare.com/auth/callback",
  "https://publications-hungarian-supporting-appearance.trycloudflare.com/auth/shopify/callback",
  "https://publications-hungarian-supporting-appearance.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://treated-virtue-nothing-broadcasting.trycloudflare.com/api/subscription"
subpath = "subscription"
prefix = "apps"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = false
