# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "16e39ea5c00ce8b931f0d050ca32e836"
application_url = "https://villa-deposit-historic-miller.trycloudflare.com"
embedded = true
name = "subscription-app-virender"
handle = "subscription-app-virender"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "https://ampland-technique-roy-due.trycloudflare.com/api/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_orders,write_own_subscription_contracts,write_products,write_purchase_options"

[auth]
redirect_urls = [
  "https://villa-deposit-historic-miller.trycloudflare.com/auth/callback",
  "https://villa-deposit-historic-miller.trycloudflare.com/auth/shopify/callback",
  "https://villa-deposit-historic-miller.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://villa-deposit-historic-miller.trycloudflare.com/api/subscription"
subpath = "subscription"
prefix = "apps"

[pos]
embedded = false
